_target_: factories.misc.make_optimizer_setup
_partial_: true
steps_per_epoch: ???
learning_rate_type: optimizer_hyperparameter
learning_rate: 5.0e-4
decay_rate: null
weight_decay: 0.0
n_epochs: ${trainer.epochs}